### ISSUE TITLE
Pearl: Alternative to stow

### ISSUE THREAD

**Issue by fsquillace** [notthebee/dotfiles#3]
I watched the video about managing dotfiles via stow:
https://www.youtube.com/watch?v=MJBVA4LeJKA

Thanks, it was quite interesting.

You might be interested on one of my project I was working on for quite a while now which helps to better modularize and sync dotfiles across different systems (Linux or OSX): https://github.com/pearl-core/pearl

It got a relative success. Maybe you can consider it for your dotfiles or for a newer youtube video ;)

**Comment by tenhishadow** [comment]
why don't just do it with ansible like this?
https://github.com/tenhishadow/dotfiles

**Comment by fsquillace** [comment]
By looking at your dotfiles I'd say there are multiple reasons for not choosing ansible :)

Very complex: I have counted something like **seven** files all related to ansible configurations and they do not have anything to do with what your git repo is meant (dotfiles). The playbook (55 lines) is something you can achieve with less than 10 lines of bash code. The playbook is something really nasty to grasp and in general Ansible has a really steep learning curve.

Dependencies: Ansible requires quite few dependencies: https://github.com/tenhishadow/dotfiles/blob/master/requirements.txt

Modularity: If someone wants to modularize its dotfiles among different repos, I'd believe that with Ansible, given its complexity, would become an epic challenge. Pearl define modularity through packages and each package can define dependencies with other packages. This means that is possible to use Pearl beyond the simple dotfiles use case such as entire programs, plugins, etc. Take a look at the [pearl hub](https://github.com/pearl-hub) for getting an idea about possible use cases.

So, why don't just do it with Pearl instead? :)

**Comment by tenhishadow** [comment]
@fsquillace 

> Modularity: If someone wants to modularize its dotfiles among different repos, I'd believe that with Ansible, given its complexity, would become an epic challenge

Ansible...complexity...epic challenge? Really?) It's very-very easy to use and which is more important - maintain

**Comment by fsquillace** [comment]
As said, having around seven files specific to Ansible just to handle few dotfiles is a huge overkill. I think Ansible is great but for certain use cases is like killing a mosquito with a bazooka.
